apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocm-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://open-cluster-management.io/helm-charts'
    targetRevision: 1.2.0
    chart: cluster-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-cluster-management
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
